package parts

// Signal is the value that actually traverses the enigma machine.
// It is generated by a Keyboard implementation, and generally is a number between 1 and 26, representing each letter in
// the alphabet.
type Signal int

// Keyboard defines a machine part that receives a character and returns a signal (number between 1 - 26)
// and a boolean (true if the conversion is ok).
type Keyboard interface {
	InputKey(key rune) (Signal, bool)
}
